micronaut:
  application:
    name: dataWarehouse
  server:
    port: 8080
netty:
  default:
    allocator:
      max-order: 3

mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
  database: warehouse
  write-concern: ACKNOWLEDGED
  collection:
    metrics: metrics
